<a href="https://colab.research.google.com/github/luccemhu/PROYECTO-1-FINAL/blob/main/index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

Para los indicadores de desarrollo global:

- Puedes ver la evolución en el tiempo de un sólo indicador, para un sólo pais, o región.
- Puedes hacer la comparación entre la evolucion de varios países.
- puedes ver la comparación entre países de un sólo indicador. Puedes enfocarte en una o varias regiones.
- puedes ver la relación de dos o más indicadores.

In [4]:
df1 = "https://raw.githubusercontent.com/luccemhu/PROYECTO-1-FINAL/main/51f7ab6a-24ed-4a06-9f5d-04873f1673fd_Data-1.csv"
# Improtamos:
desa_global = pd.read_csv(df1, encoding = "latin-1")

desa_global.columns= desa_global.columns.str.lower() # minuscula
desa_global

,country name,country code,series name,series code,1960 [yr1960],1961 [yr1961],1962 [yr1962],1963 [yr1963],1964 [yr1964],1965 [yr1965],...,2013 [yr2013],2014 [yr2014],2015 [yr2015],2016 [yr2016],2017 [yr2017],2018 [yr2018],2019 [yr2019],2020 [yr2020],2021 [yr2021],2022 [yr2022]
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,..,..,..,..,..,..,...,68.0408782958984,89.5,71.5,97.7,97.7,93.4308776855469,97.7,97.7,97.7,..
1,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,..,..,..,..,..,..,...,60.2391977225107,86.5005116269173,64.5733543829493,97.0993598284929,97.0919732482142,91.6060600230095,97.0756269501314,97.0667125932952,97.0572022178384,..
2,Afghanistan,AFG,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,..,..,..,..,..,..,...,0.29808781267706,0.283692395910162,0.297971774718822,0.268358772656602,0.281195815732375,0.299082634225993,0.297563650500103,0.223478872007068,..,..
3,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,..,..,..,..,..,..,...,5.60074465808174,2.72454336394887,1.45131466009762,2.26031420130457,2.6470032019574,1.18922812838036,3.91160341942292,-2.3511006734461,-20.7388393676343,..
4,Afghanistan,AFG,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,0.170626997947693,..,..,..,..,..,...,0.53,0.5,0.5,0.5,0.39,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,Last Updated: 12/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#desa_global.info()

In [7]:
desa_global.replace("..", np.nan, inplace=True)

med_fill = desa_global.median(numeric_only=True)

desa_global.fillna(med_fill)

,country name,country code,series name,series code,1960 [yr1960],1961 [yr1961],1962 [yr1962],1963 [yr1963],1964 [yr1964],1965 [yr1965],...,2013 [yr2013],2014 [yr2014],2015 [yr2015],2016 [yr2016],2017 [yr2017],2018 [yr2018],2019 [yr2019],2020 [yr2020],2021 [yr2021],2022 [yr2022]
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,68.0408782958984,89.5,71.5,97.7,97.7,93.4308776855469,97.7,97.7,97.7,NaN
1,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.2391977225107,86.5005116269173,64.5733543829493,97.0993598284929,97.0919732482142,91.6060600230095,97.0756269501314,97.0667125932952,97.0572022178384,NaN
2,Afghanistan,AFG,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,NaN,NaN,NaN,NaN,NaN,NaN,...,0.29808781267706,0.283692395910162,0.297971774718822,0.268358772656602,0.281195815732375,0.299082634225993,0.297563650500103,0.223478872007068,NaN,NaN
3,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.60074465808174,2.72454336394887,1.45131466009762,2.26031420130457,2.6470032019574,1.18922812838036,3.91160341942292,-2.3511006734461,-20.7388393676343,NaN
4,Afghanistan,AFG,"Hospital beds (per 1,000 people)",SH.MED.BEDS.ZS,0.170626997947693,NaN,NaN,NaN,NaN,NaN,...,0.53,0.5,0.5,0.5,0.39,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,Last Updated: 12/18/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#df_global = desa_global.copy(deep = True)

desa_global.replace("..", np.nan, inplace=True)

clean_global = desa_global.dropna()
clean_global

Empty DataFrame
Columns: [country name, country code, series name, series code, 1960 [yr1960], 1961 [yr1961], 1962 [yr1962], 1963 [yr1963], 1964 [yr1964], 1965 [yr1965], 1966 [yr1966], 1967 [yr1967], 1968 [yr1968], 1969 [yr1969], 1970 [yr1970], 1971 [yr1971], 1972 [yr1972], 1973 [yr1973], 1974 [yr1974], 1975 [yr1975], 1976 [yr1976], 1977 [yr1977], 1978 [yr1978], 1979 [yr1979], 1980 [yr1980], 1981 [yr1981], 1982 [yr1982], 1983 [yr1983], 1984 [yr1984], 1985 [yr1985], 1986 [yr1986], 1987 [yr1987], 1988 [yr1988], 1989 [yr1989], 1990 [yr1990], 1991 [yr1991], 1992 [yr1992], 1993 [yr1993], 1994 [yr1994], 1995 [yr1995], 1996 [yr1996], 1997 [yr1997], 1998 [yr1998], 1999 [yr1999], 2000 [yr2000], 2001 [yr2001], 2002 [yr2002], 2003 [yr2003], 2004 [yr2004], 2005 [yr2005], 2006 [yr2006], 2007 [yr2007], 2008 [yr2008], 2009 [yr2009], 2010 [yr2010], 2011 [yr2011], 2012 [yr2012], 2013 [yr2013], 2014 [yr2014], 2015 [yr2015], 2016 [yr2016], 2017 [yr2017], 2018 [yr2018], 2019 [yr2019], 2020 [yr2020], 2021 [yr2021], 2022 [yr2022]]
Index: []

[0 rows x 67 columns]

In [9]:
clean_global.shape

(1596, 67)

In [6]:
clean_global.dropna().shape

#nomb_variables = clean_global.columns
#nomb_variables

(1596, 67)

In [6]:
# puedes ver la evolución en el tiempo de un sólo indicador, para un sólo pais, o región.

happy_peru = happy_all[happy_all['Country name'] == 'Peru']

elem1 = alt.Chart(happy_peru).mark_line().encode(
x = alt.X('year'),
y = alt.Y('Life Ladder:Q'))

elem1

In [6]:
# puedes ver la relación de dos o más indicadores.
alt.Chart(happy).mark_point().encode(
    x = alt.X("Life Ladder:Q"),
    y = alt.Y("Log GDP per capita:Q"),
    color = "Regional indicator",
    tooltip = ["Country name", "Life Ladder"]
    ).interactive()

In [6]:
# GRÁFICO DE BARRAS

alt.Chart(happy_lac).mark_bar().encode(
y = alt.Y("Life Ladder"),
x = alt.X("Country name"))